### ISSUE TITLE
Choix de DB

### ISSUE THREAD

**Issue by DrPandemic** [DrPandemic/mcoo-gn#1]
Nous n'avons pas encore décidé quel base de données nous allions utiliser pour le backend. Nous avons plusieurs choix. Soit nous prennons une DB relationnelle (MySql/Postgresql/sqlite) ou une une DB objet (MongoDB parce que c'est bien intégré à Node).

# DB
## Relationnelle
MySql et Postgresql sont assez semblable pour ce que nous avons besoin de faire. Par contre, MySql est un peu moins intrusif une fois installé, alors ca peut être sympatique quand on dev. L'avantage de sqlite est que c'est super lightweight et il n'y a pas de gossage à faire pour s'occuper du serveur de DB, il n'y en a pas. Sqlite roule dans le process de l'application.
## Objet
Ca nous permettrais d'apprendre une nouvelle technologie assez plaisante à utiliser. Par contre un bémol, pour nos amis qui roulent winodws, MongoDB roule sur 7 et up. Est-ce que quelqu'un est encore sur XP/Vista?

# ORM
Nous devons aussi décider si nous voulons utiliser un ORM ([Object-relational mapping](https://en.wikipedia.org/wiki/Object-relational_mapping)). En résumer, les ORM sont des librairies qui abstraient l'utilisation de la DB. On ne créer pas de schéma (quoi que ca existe pas sur MongoDB), on définit des objets et la librairie s'occupe des les load/save. Si nous n'utiliserons pas d'ORM, nous devrons faire nos query à bras.

SQL
```sql
SELECT ID, CITY, STATE FROM STATION
```
MongoDB
```javascript
db.inventory.find( { type: { $in: [ 'food', 'snacks' ] } } )
```

Exemple pour [sequelize](http://docs.sequelizejs.com/en/latest/docs/models-definition/) un ORM pour des DB relationnelles
```javascript
//Definit le schema en DB d'un chat
var Kitten = sequelize.define('Kitten', {
  name: {type: Sequelize.STRING, allowNull: false, defaultValue: 'cake'}
});

//Creer un chat
Kitten.create({ name: 'Fluffy' })
.then(function(employee) {
  console.log(employee.get('name'));
})

//Cherche un chat
Kitten.findAll({ where: { name: 'Fluffy' } })
.then(function(kittens) {
  console.log(kittens);
})
```

Exemple pour [mongoose](http://mongoosejs.com/docs/index.html) un ORM pour MongoDB
```javascript
//Definit le schema en DB d'un chat
var kittySchema = mongoose.Schema({
    name: String
});
//Le model est un objet que l'on utilise pour instatier des chats
var Kitten = mongoose.model('Kitten', kittySchema);

//Creer un chat
var fluffy = new Kitten({ name: 'Fluffy' });

...

//Cherche dans la DB des chat dont le nom fait partie de ce regex /^Fluff/
Kitten.find({ name: /^Fluff/ }, function (err, kittens) {
  if (err) return console.error('Une erreur est survenue');
  console.log(kittens);
});
```

Je n'ai pas beaucoup travaillé avec des ORM, mais à ce que je comprend de la doc, sequelize semble plus puissant, mais plus complexe.

# Question finale
Alors que pensez-vous de tout cela? Quel DB voulez-vous utiliser et utiliserons-nous un ORM? Personnellement, je pense que prendre un ORM va simplement nous faire gagner du temps même si on ne connait pas tant ca.

**Comment by MicLamb** [comment]
Bonjour à tous mon nom est Michaël. Pour ma part, j'hésite beaucoup parce que malgré que Mongo s'intègre bien à Node, il me semble que ça commence à faire beaucoup de nouveauté. Ce serait bien que back ou front, les gens ayant un peu moins connaisseurs puissent au moins avoir une technologie qu'ils connaissent pour ne pas se décourager de passer leur temps sur des forums pour essayer de faire fonctionner quelque chose.

Donc ma réponse c'est une BD avec SQL pour qu'au moins nous connaissions ça XD. 

Pour l'ORM aussi c'est un peu nouveau mais je pense que l'intégrer avec une BD relationnelle c'est surment pas si pire que ça en a l'air donc OK pour l'ORM

**Comment by DrPandemic** [comment]
Ceci est un [exemple](http://docs.sequelizejs.com/en/1.7.0/articles/express/) assez simple pour utiliser sequelize avec sqlite3

**Comment by JesseEmond** [comment]
Peu importe lequel.

**Comment by Baltazar510** [comment]
Pour ma part, je dois dire que MongoDB semble intéressent, et simple a utilisé.
Se serais mon premier choix
Mais, si y'a du monde insécure, on peut prendre du SQL

**Comment by pellerinse2302** [comment]
Personnellement j'irais plus avec du SQL, mais je ne suis pas fermé à l'idée d'essayer quelque chose de nouveau.

**Comment by bluespart** [comment]
L'un ou l'autre ne me dérange pas. J'ai un penchant pour MongoDB + ORM, mais je ne vois aucun problème a un setup SQL + ORM.

**Comment by VincentHamel** [comment]
l'ORM semble etre un must pour tout ceux qui travaillerons avec des BD plus tard donc oui.

je suis neutre sur la question BD objet VS BD relationnelle... mais j'ai seulement travailler avec des BD relationnelle jusqu'a présent

**Comment by Erikad94** [comment]
MongoDB, pour ma raison preferer c'est cool voir de nouvelles choses pis de toute facon ca a l'air assez facile a utiliser
