### ISSUE TITLE
Nom de projet

### ISSUE THREAD

**Issue by JesseEmond** [DrPandemic/mcoo-gn#10]
Il nous faudrait un nom pour le projet (pour le document d'équipe/personnel, entre autres choses).

Je proposerait `Pocket GN` ou quelque chose du genre.

Quelqu'un a une idée? Je pense que le nom n'est pas *trop* important et que c'est surtout pour avoir un *code-name* qu'on peut donner dans la documentation.

S.v.p. votez ou donnez de meilleures idées.

**Comment by DrPandemic** [comment]
Je t'avou pas avoirde meilleur idée, so ```Pocket GN``` c'est cool.

**Comment by Erikad94** [comment]
c'est bizarre comme nom parce que t'as melanger de l'anglais pis du francais :P

**Comment by DrPandemic** [comment]
Si tu le dis avec un accent anglais, ca passe tres bien :)

**Comment by MicLamb** [comment]
<code>Pocket LARP</code> ou <code>GN de poche</code>

**Comment by VincentHamel** [comment]
Je propose Wabajaba

pour aucune raison particuliere.
