### ISSUE TITLE
Jalon 1

### ISSUE THREAD

**Issue by DrPandemic** [DrPandemic/mcoo-gn#15]
Il faudrait qu'on décide ce qu'il y a dans le premier jalon et quel est la date limite. Merci de commenter

**Comment by JesseEmond** [comment]
Je propose:

frontend: affichage des infos d'un personnage, SOIT en se connectant avec un vrai serveur, SOIT en utilisant du fake data (donc, déjà avoir dequoi qui nous permet de faker une connexion, qui nous permettra de bien unit-tester)

backend: répondre aux GETs de personnages & lire de la DB. Si on a le temps (mais ne fait pas parti du jalon), CRUD?

Proposez des modifs/une date. :)

**Comment by Erikad94** [comment]
Jesse est-ce que tu peux les separer en issues/ le temps que tu pense que ca prendrait pour qu'on puisse savoir combien de temps on passe dessus/combien de temps le jalon doit durer?

**Comment by JesseEmond** [comment]
frontend (selon ma perception, avec des noms changeables):
- modeler personnage côté client (objet `Character`) (~1-2h)
- afficher infos d'un personnage (interface `ICharacterRepository`, implémentée par `FakeCharacterRepository` qui retourne des faux objets `Character`s). `ICharacterRepository` aurait une fonction `getCharacter(id)` qui sera utilisée avec un id fixe pour l'instant. (~2-3h)
- connexion avec backend pour affichage de persos (`ApiCharacterRepository` qui implémente `ICharacterRepository` et qui fait le bon GET au serveur et transforme l'objet JSON en vrai objet `Character` (~3-4h)

backend:
- modeler character, dans Mongo (~1-2h), *idéalement* des tests unitaires de validité d'un character
- `GET /characters/:id`, retourne un faux personnage pour l'instant (<1h)
- GET character retourne le vrai personnage, fait le call à mongodb (~1-2h)
- RUD character et validations (optionnel) (~3-4h)

**Comment by DrPandemic** [comment]
Je sens que l'android sera un peu plus long. Mais encore la, cest juste que je ne connais pas ca

**Comment by JesseEmond** [comment]
@DrPandemic je prenais en considération qu'on a un GET fonctionnel ici, mais tu as raison. Je vais augmenter les estimés. Les tâches te vont?

**Comment by Erikad94** [comment]
Faq en tout on aurait 18-24h donc ~2h par personne... si on a 2-3 jalon je ne pense pas que c'est assez

**Comment by DrPandemic** [comment]
Faut pas mélanger jalon et sprint. Jalon c'est juste un lock. So ca veut pas dire quil seront tous aussi long

**Comment by Erikad94** [comment]
Mais, si on en a juste 2-3 faut pas qu'ils soit quand meme un peut constant? Pis ca nous sert a quoi d'avoir des jalons et des sprints dans un projet aussi petit?

**Comment by VincentHamel** [comment]
j'ai une ebauche d'objet character.

a vrai dire j'avais commencer un peu selon le schéma envoyé par Email: une personne est soit un joueur ou un employé, un joueur possede un ou plusieurs character. un character contiens (pour l'instant) grosso modo un paquet de string.

getters-setters-init.

inc sur github... soon.... ish...

**Comment by VincentHamel** [comment]
fuck that. Email inc.

**Comment by MicLamb** [comment]
Ok je pense qu'on a tous un gros problème de coordination. Premièrement, on doit passer du temps sur ce qui est nécessaire pour l'accomplissement du jalon en cours. Il n'y a pas lieu d'aller plus rapidement que le projet lui-même, c'est tout au contraire de ce qu'est le SCRUM parce que si quelque chose dans le design change, on pourrait peut-être être obligé de tout "wipper" les avancements faits. 

Les tâches de de jalon 1 me semble correctes. Il faudrait donc en faire des issues et que les personnes qui travaillent dessus se les approprient en y mettant le label "working on". De plus, en théorie, le coût des tâches (et non pas la durée) devrait être déterminé avec toute l'équipe. En SCRUM on ne définit pas une tâche avec une durée en heure.

Compte tenu des délais, on peut skipper cette première partie de détermination du coût des tâches et les passer directement en issues : cependant il faudra à l'avenir que ce soit selon un coût déterminé en équipe.

Vous allez probablement me trouver "désagré" mais il faudrait un peu plus de discipline à suivre ces règles qui sont importantes pour le succès de ce projet, et par succès je ne parle pas d'obtenir un produit fini mais bien d'avoir suivi le processus SCRUM et d'avoir une petite version fonctionnelle après chaque jalon/sprint.

Merci de m'avoir écouté me vider le coeur.

**Comment by Erikad94** [comment]
Dans le meilleur des mondes il faut qu'on finisse avant les examens (pour pouvoir etudier et autre) Ce qui veux dire qu'il nous reste 2 mercredi pour regler nos problemes d'agile. 

- Il faut qu'on determine notre etalon d'exemple pour pouvoir se baser sur quelque chose quand on determine notre cout. (utiliser un cout en heure est peut-etre mieux pour nous puisqu'on a un contrainte d'heure pour notre projet. Ne pas oublier que la methode agile peut etre modifier pour nos besoins) Determiner un cout pour nous puisque notre projet est petit et que nous ne sommes pas familier avec un etalon va etre plutot difficile parce que nous n'avons pas d'etalon commun.
-Il faut planifier le sprint (tous les issues a faire dans le sprint) et determiner qui fait quoi et pour quand (ne pas oublier que cest du peer programming)
-Il faut revenir sur le dernier sprint pour voir qu'est-ce qu'il y a a ameliorer et comment
-Notre probleme c'est qu'on a pas fait ca au debut, on a pas de scrum master qui determine ca. Je veux pas te blamer Mic, mais nous aurions du vrm pousser pour que le scrum master le fasse puisque c'est vrm sa tache a faire fonctionner tous le systeme d'agile. Il faudra vrm determiner le scrum master qui va vrm tous trancher et gerer les meetings et s'assurer que tous sache qu'est-ce qu'il faut faire et quand.
...

**Comment by MicLamb** [comment]
En effet Erika, c'est moi le Scrum Master et j'ai oublié de faire la planification du jalon un mercredi : c'est mon erreur.
