### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by MicLamb** [DrPandemic/mcoo-gn#29]
Frontend
Coût : 5

Faire la page d'authentification avec un appel au serveur et la validation de l'utilisateur du côté serveur afin d'accéder à la page suivante.

**Comment by Erikad94** [comment]
working on

**Comment by MicLamb** [comment]
Working on with @pellerinse2302

**Comment by MicLamb** [comment]
Simple Regex validation done on the email for the moment. We will update it when the backend can verify if the email and password are valid.

**Comment by MicLamb** [comment]
Merged
