### ISSUE TITLE
Schema de DB

### ISSUE THREAD

**Issue by DrPandemic** [DrPandemic/mcoo-gn#3]
Avoir le schema de doit ou les objets de l'ORM

**Comment by DrPandemic** [comment]
Je propose cette structure de données. C'est basé sur les fiche de perso, mais un peu simplifié.
```
player :
{
	name: string,
	phone: string,
	email: string,
	characters: [character]
}

character :
{
	name: string,
	nationality: string,
	race: enum race,
	profession: enum profession,
	class: enum class,
	belief: string,
	max_hp: int,
	skills: [enum skill],
	xp: int
}

race : [humain, elf, dwarf]

profession : [botanist, miner, forgeron, scribe, trader]

class : [warrior, wizard, bard, priest, thief]

skill : [ambidextrous, berserk, meditation, estimate, decrypt, concentration, trading, hypnosis]
```

**Comment by MicLamb** [comment]
Yo start the project it looks enough for me! If we think there's a miss we will be able to add it easily in the project so LGTM (Let's Get This Money).

**Comment by Erikad94** [comment]
Il faudrait aussi des users et peut etre une facon de dire que le character est mort/inactif?

**Comment by DrPandemic** [comment]
Je ne pense que cest important d'avoir mort/incatif, parce que l'app ne sera surement pas utilisé durant le GN, mais bien après et je pense qu'à chaque debut de GN tout le monde est vivant.

**Comment by Erikad94** [comment]
Ouin, mais faut pas mettre d'exp sur un perso mort non? ou ils n'existerait plus tout court?

**Comment by DrPandemic** [comment]
Je ne suis vraiment pas sur. Mais je pense quil ne serait juste pu la...

**Comment by JesseEmond** [comment]
:+1:  pour la structure, me semble très bien.
