### ISSUE TITLE
Listing User's characters

### ISSUE THREAD

**Issue by MicLamb** [DrPandemic/mcoo-gn#30]
Frontend
Coût : 5

Faire la liste des personnages de l'utilisateur en faisant la requête vers le serveur et en faisant l'authentification de l'utilisateur.

**Comment by VincentHamel** [comment]
working on (affichage d'abord)

**Comment by VincentHamel** [comment]
affichage basique
Victoire contre les spinners diaboliques... il affiche maintenant du fake data.

Dance de joie de la part de Nunj.

Next: chaque entry du spinner redirige vers la feuille de character deja faite (?)

**Comment by VincentHamel** [comment]
ATTENTION

erreur dans le code: le constructeur de character demande un List<string> en parametre, OR... c'est un type abstrait de java et on peut pas en envoyer. 

j'ai donc changer tout les List<string> par un tableau de string.

**Comment by Erikad94** [comment]
Liste est une interface utilise ArrayListe qui est une implementation de Liste

**Comment by MicLamb** [comment]
Merged.
