### ISSUE TITLE
Structure de données

### ISSUE THREAD

**Issue by DrPandemic** [DrPandemic/mcoo-gn#9]
Faire les classes java qui représente les données du character

**Comment by JesseEmond** [comment]
S'inspirer de #3 pour les informations pertinentes à conserver.

**Comment by VincentHamel** [comment]
j'ai fait le rough draft inspiré du document Syranty sur excel...apparament je peut pas le transférer sur github et une simple image serais pas trop utile... donc retour au technique de base: email

**Comment by Erikad94** [comment]
me and jesse the douche are working on it
